### ISSUE TITLE
/root/go/bin/s3bench --version shows empty version string

### ISSUE THREAD

**Issue by ketanarlulkar** [Seagate/s3bench#17]
Steps:
1. Installed s3bench using `go get github.com/Seagate/s3bench`
2. /root/go/bin/s3bench --version gives "-" as output instead of s3bench version.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28435. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by t7ko-seagate** [comment]
This is expected behavior.  There is no way to embed git version using `go get` approach.

To create a build which has a working `--version`, you will need to use `./build.sh` script.

Best way is to download one of pre-created builds, see here: https://github.com/Seagate/s3bench/releases

If you want to build yourself:

* check out source code
* cd s3bench.git
* ./build.sh
  * build may be failing due to missing dependencies.  Follow the on-screen instructions to install missing dependencies, then re-run `./build.sh`

**Comment by t7ko-seagate** [comment]
I have updated README.md with the same information.

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

Reviewed

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

Resolved

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

Closed
